[package]
name = "hello_window"
edition = "2021"

[dependencies]
mapsdk = { path = "../../mapsdk" }
env_logger.workspace = true
geo.workspace = true
log.workspace = true
pollster.workspace = true
rand.workspace = true
winit.workspace = true
